apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: app-container
      image: busybox
      # command: [ "app" ]
      # args: [ "-config", "/app/config.yaml" ]
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'until nslookup myapp; do echo waiting for myapp; sleep 2; done;']
